spring.application.name=server
server.port=8083

# JSON 출력 시 날짜/시간 포맷 지정
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss
# 뉴질랜드 타임존 설정 (오클랜드 기준)
spring.jackson.time-zone=Pacific/Auckland
# Hibernate가 DB에 시간을 저장할 때 사용할 타임존
spring.jpa.properties.hibernate.jdbc.time_zone=Pacific/Auckland
#private static final String SECRET = "my-secret-key-my-secret-key";
#private static final long ACCESS_EXP = 1000 * 60 * 30; // 30분
#private static final long REFRESH_EXP = 1000L * 60 * 60 * 24 * 7; // 7일

jwt.secret=vu33zFAd3EHq9APg0qgY+8lUia4Ue0YQG/dPcKXsgl4EZ14wJcA7YOnzFFWmUxmcCG9dxhAV5rCf5Y3ZU8ir4g==
jwt.access-exp=1800000
jwt.refresh-exp=604800000

spring.datasource.url=jdbc:mysql://localhost:3306/pos2026?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.username=posuser
spring.datasource.password=possystem123!@#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ddl-auto: validate (테이블 구조만 검증, 변경 X)
spring.jpa.hibernate.ddl-auto=update
# SQL 로그 비활성화 : false (성능 + 로그 정리)
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# INFO / DEBUG / WARN / ERROR 대부분 제거
logging.level.com.swna.server=ERROR